### ISSUE TITLE
create measurement picker for PMUs

### ISSUE THREAD

**Issue by rajku209** [nagasudhirpulla/electron_react_dashboard#20]

**Comment by nagasudhirpulla** [comment]
https://datatables.net/examples/api/select_single_row.html
Jquery datatable single row selection and click callback

**Comment by nagasudhirpulla** [comment]
https://datatables.net/examples/data_sources/js_array.html - Jquery datatables array initialization

**Comment by nagasudhirpulla** [comment]
implemented in v3.1.0
